services:
  - type: web
    name: ram-file-share
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/status
    autoDeploy: true

  - type: web
    name: ram-file-share-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ram-file-share-api.onrender.com
    autoDeploy: true 